project:
  type: website
  title: "AgriPredict"
  output-dir: docs

website:
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Reports"
        href: projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/showcase/ppgeps-ppucpr
      - icon: github
        href: https://pibicagrofinance.github.io/site/
      - icon: whatsapp
        href: https://chat.whatsapp.com/BWw4C46eSJ1EMq1EGflcOK
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Commodities IA Team, AgriPredict"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Intro"
        href: introduction.qmd
        contents: 
          - index.qmd
          - mindmap.qmd
          - interactivemindmap.qmd
          - revsyslit.qmd
      - section: "Commodities (grains) news"
        href: news.qmd
        contents:
          - news_google_trends.qmd
          - openAi_agent.qmd
      - section: "Predictive Models"
        href: predictive_model.qmd
        contents:
          - time_series_portfolio.qmd
          - markovian_bayesian_timeseries.qmd
          - machine_learning_models.qmd
          - econometrics_model_sel.qmd
      - section: "MultiObjective Multiperiod Optimization"
        href: optimization.qmd
        contents:
          - portfolio_multiobj_opt_algos.qmd
          - scenario_simulation_fuzzy_multicriteria.qmd
          - layout-jupyter.qmd
      - section: "Reinforcement Learning Strategies"
        contents:
          - pareto_front_reinforcement.qmd
          - reinforcement_algos_decision_making.qmd
      - href: acknowlegment.qmd

format:
  html:
    theme: cosmo
    css: styles.css




